---
# Kubernetes manifest for AI Finance Application
apiVersion: v1
kind: Namespace
metadata:
  name: ai-finance

---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-finance-config
  namespace: ai-finance
data:
  # Application Settings
  NODE_ENV: "production"
  PORT: "3000"
  FRONTEND_PORT: "3001"

  # AI/LLM Configuration (Google Gemini)
  AI_PROVIDER: "gemini"
  AI_MODEL: "gemini-1.5-flash"
  # Note: API URL not needed for Gemini (uses https://generativelanguage.googleapis.com)

  # Database Configuration
  DATA_DIR: "./data"

  # Kubernetes Configuration
  K8S_NAMESPACE: "ai-finance"

  # Logging & Debug
  LOG_LEVEL: "info"
  DEBUG: "false"

---
# Secret for sensitive environment variables (Google Gemini API Key)
apiVersion: v1
kind: Secret
metadata:
  name: ai-finance-secret
  namespace: ai-finance
type: Opaque
stringData:
  # ⚠️  REQUIRED: Replace 'your_actual_gemini_api_key_here' with your actual Gemini API key
  # Get your key from: https://ai.google.dev/tutorials/setup
  # Note: This key is required for AI financial advice generation
  AI_API_KEY: "your_actual_gemini_api_key_here"

---
# PersistentVolumeClaim for backend data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data-pvc
  namespace: ai-finance
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Gi

---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-finance-backend
  namespace: ai-finance
  labels:
    app: ai-finance-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ai-finance-backend
  template:
    metadata:
      labels:
        app: ai-finance-backend
        version: v1
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1001
      containers:
        - name: backend
          image: leratomatamela1/ai-finance-backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: ai-finance-config
            - secretRef:
                name: ai-finance-secret
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: backend-data-pvc

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: ai-finance-backend-svc
  namespace: ai-finance
  labels:
    app: ai-finance-backend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ai-finance-backend

---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-finance-frontend
  namespace: ai-finance
  labels:
    app: ai-finance-frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ai-finance-frontend
  template:
    metadata:
      labels:
        app: ai-finance-frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: leratomatamela1/ai-finance-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2

---
# Frontend Service (LoadBalancer for external access)
apiVersion: v1
kind: Service
metadata:
  name: ai-finance-frontend-svc
  namespace: ai-finance
  labels:
    app: ai-finance-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ai-finance-frontend

---
# Ingress for routing (optional)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-finance-network-policy
  namespace: ai-finance
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ai-finance
        - podSelector: {}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: ai-finance
        - podSelector: {}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53

---
# RBAC - ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-finance-sa
  namespace: ai-finance

---
# RBAC - Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-finance-role
  namespace: ai-finance
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

---
# RBAC - RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-finance-rolebinding
  namespace: ai-finance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ai-finance-role
subjects:
  - kind: ServiceAccount
    name: ai-finance-sa
    namespace: ai-finance

---
# HorizontalPodAutoscaler for backend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: ai-finance
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-finance-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
# HorizontalPodAutoscaler for frontend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: ai-finance
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-finance-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
